# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LWP-UserAgent-OfflineCache
version:      0.02
version_from: lib/LWP/UserAgent/OfflineCache.pm
installdirs:  site
requires:
    HTTP::Message:                 0
    IO::All:                       0
    Log::Log4perl:                 0
    LWP:                           0
    LWP::UserAgent:                0
    Moose:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
